Repository titicacadev/triple-frontend, pull requests merged in 2022-01, with the labels that each got.

#1841 map 디렉토리의 ESLint 검사를 활성화하고 오류를 수정합니다.
  .eslintignore
  packages/map/src/index.tsx
  packages/map/src/marker/index.ts
  packages/map/src/marker/with-type-circle-marker.tsx
  packages/map/src/utilities.ts
Labels: help wanted

#1787 💥 ad-banners의 ListDirection enum의 멤버 네이밍 변경
  packages/ad-banners/src/list-top-banners.tsx
  packages/ad-banners/src/typing.ts
Labels: help wanted, Breaking Change

#1863 [react-contexts] user-agent-context의 isPublic과 app 속성에 deprecation notice를 추가합니다.
  packages/react-contexts/src/user-agent-context/utils.ts
Labels: :pouch: react-contexts

#1867 📦 update package-lock.json
  package-lock.json
Labels: help wanted

#1874 [poi-detail] `image-carousel` 내부의 노트 컴포넌트를 수정합니다
  packages/poi-detail/src/image-carousel/carousel-section.tsx
  packages/poi-detail/src/image-carousel/note.tsx
Labels: ℹ️poi-detail
