Repository titicacadev/triple-frontend, pull requests merged in 2022-02, with the labels that each got.

#1890 v6 마이그레이션 가이드에 react-triple-client-interfaces에 대응하는 내용을 추가합니다.
  MIGRATION.md
Labels: :page_with_curl: documentation

#1900 [poi-detail] PoiDetail 의 NoteContainer 수정으로 인해 생겼던 버그를 수정합니다.
  packages/poi-detail/src/image-carousel/carousel-section.tsx
  packages/poi-detail/src/image-carousel/note.tsx
Labels: :bug: bug

#1904 [map] `flexibleMarker`에 누락된 props을 추가합니다
  packages/map/src/overlay/markers/flexible-marker.tsx
Labels: help wanted

#1933 ✨ CommonMeta에 manifest link 엘리먼트 추가
  packages/meta-tags/src/common-meta.tsx
Labels: help wanted

#1934 [replies] 닉네임이 9자 이상일 때, 말줄임표로 표기합니다.
  packages/replies/src/list/reply.tsx
Labels: help wanted

#1949 [replies] 답글을 생성 시간 기준으로 오름차순 정렬합니다.
  packages/replies/src/replies.tsx
Labels: help wanted
